import { ShaderGradient, ShaderGradientCanvas } from '@shadergradient/react';

export default function NightyNightShader() {
  return (
    <ShaderGradientCanvas
      className="nighty-night-canvas"
      pointerEvents="none"
      pixelDensity={1}
      fov={45}
      lazyLoad
      powerPreference="low-power"
    >
      <ShaderGradient
        animate="on"
        axesHelper="off"
        brightness={1}
        cAzimuthAngle={180}
        cDistance={2.8}
        cPolarAngle={80}
        cameraZoom={9.1}
        color1="#1e5a58"
        color2="#80b09e"
        color3="#0d1514"
        destination="onCanvas"
        embedMode="off"
        envPreset="city"
        format="gif"
        fov={45}
        frameRate={10}
        gizmoHelper="hide"
          grain="off"
        lightType="3d"
        pixelDensity={1.5}
        positionX={0}
        positionY={0}
        positionZ={0}
        range="disabled"
        rangeEnd={40}
        rangeStart={0}
        reflection={0.1}
        rotationX={50}
        rotationY={0}
        rotationZ={-60}
        shader="defaults"
        type="waterPlane"
        uAmplitude={0}
        uDensity={1.6}
        uFrequency={0}
        uSpeed={0.3}
        uStrength={2}
        uTime={8}
        wireframe={false}
      />
    </ShaderGradientCanvas>
  );
}